// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj__D7SqgH-uj-DsrAketizhHsrXLOkO0',
    appId: '1:280131379669:web:8a0337be68f411a64d5d5c',
    messagingSenderId: '280131379669',
    projectId: 'doxy-e879c',
    authDomain: 'doxy-e879c.firebaseapp.com',
    storageBucket: 'doxy-e879c.firebasestorage.app',
    measurementId: 'G-HEF9YKDGH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhDDuh4KnPS1dnfzLO3hME0DL81XKMk8Q',
    appId: '1:280131379669:android:da94a5f48b9972ec4d5d5c',
    messagingSenderId: '280131379669',
    projectId: 'doxy-e879c',
    storageBucket: 'doxy-e879c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4I8eTopQBkg9Dbt4l4rUD6OsfVlJM4zo',
    appId: '1:280131379669:ios:9913b0ba67248bab4d5d5c',
    messagingSenderId: '280131379669',
    projectId: 'doxy-e879c',
    storageBucket: 'doxy-e879c.firebasestorage.app',
    androidClientId:
        '280131379669-3bqjkadsn6h5s9s7a4p8vo1comf0gl0f.apps.googleusercontent.com',
    iosBundleId: 'com.doxys.doxyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4I8eTopQBkg9Dbt4l4rUD6OsfVlJM4zo',
    appId: '1:280131379669:ios:9913b0ba67248bab4d5d5c',
    messagingSenderId: '280131379669',
    projectId: 'doxy-e879c',
    storageBucket: 'doxy-e879c.firebasestorage.app',
    androidClientId:
        '280131379669-3bqjkadsn6h5s9s7a4p8vo1comf0gl0f.apps.googleusercontent.com',
    iosBundleId: 'com.doxys.doxyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj__D7SqgH-uj-DsrAketizhHsrXLOkO0',
    appId: '1:280131379669:web:d9b0f5717a5dd6434d5d5c',
    messagingSenderId: '280131379669',
    projectId: 'doxy-e879c',
    authDomain: 'doxy-e879c.firebaseapp.com',
    storageBucket: 'doxy-e879c.firebasestorage.app',
    measurementId: 'G-6Y41785QLY',
  );
}
